import { useState, useEffect } from 'react';
import { ChevronDown, ChevronUp, Loader2 } from 'lucide-react';
import { generateAIResponse } from '../services/ai';

export default function Experiences() {
    const [openIndex, setOpenIndex] = useState(null);
    const [loading, setLoading] = useState(false);
    const [interviewQuestions, setInterviewQuestions] = useState([]);
    const [targetRole, setTargetRole] = useState('');
    const [targetCompany, setTargetCompany] = useState('');

    useEffect(() => {
        // Get target role and company from localStorage (set from Dashboard)
        const storedRole = localStorage.getItem('targetRole') || 'Software Engineer';
        const storedCompany = localStorage.getItem('targetCompany') || 'Tech Company';
        setTargetRole(storedRole);
        setTargetCompany(storedCompany);

        // Generate questions on mount
        generateQuestions(storedRole, storedCompany);
    }, []);

    const generateQuestions = async (role, company) => {
        setLoading(true);
        try {
            const prompt = `You are an interview preparation expert. Generate 6 common interview questions with detailed answering strategies for a ${role} position at ${company}.

Format your response EXACTLY like this:

Q1: [Question text]
STRATEGY: [Detailed strategy for answering this question, 2-3 sentences]

Q2: [Question text]
STRATEGY: [Detailed strategy for answering this question, 2-3 sentences]

Continue for all 6 questions. Make the questions specific to the role and company.`;

            const response = await generateAIResponse(prompt);

            const questions = [];
            const questionMatches = response.matchAll(/Q\d+:\s*(.+?)\nSTRATEGY:\s*(.+?)(?=\n\nQ\d+:|$)/gs);

            for (const match of questionMatches) {
                questions.push({
                    question: match[1].trim(),
                    strategy: match[2].trim()
                });
            }

            setInterviewQuestions(questions);
        } catch (error) {
            console.error('Error generating questions:', error);
            // Fallback to generic questions
            setInterviewQuestions([
                {
                    question: 'Tell me about yourself',
                    strategy: 'Start with a brief professional summary, highlight your most relevant experience, and connect it to why you\'re interested in this role. Keep it concise (2-3 minutes) and focus on your career journey.'
                },
                {
                    question: 'Why do you want to work here?',
                    strategy: 'Research the company beforehand. Mention specific products, values, or initiatives that resonate with you. Connect your skills and career goals to what the company offers.'
                },
                {
                    question: 'What are your strengths and weaknesses?',
                    strategy: 'For strengths, choose 2-3 that are relevant to the role with specific examples. For weaknesses, pick something genuine but not critical, and explain how you\'re actively working to improve it.'
                }
            ]);
        } finally {
            setLoading(false);
        }
    };

    const toggleAccordion = (index) => {
        setOpenIndex(openIndex === index ? null : index);
    };

    return (
        <div style={{ maxWidth: '900px', margin: '0 auto' }} className="fade-in">
            <h1 style={{ fontSize: '2rem', fontWeight: '600', marginBottom: '0.5rem' }}>Interview Questions & Tips</h1>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '0.5rem', fontSize: '1.05rem' }}>
                Related to <strong>{targetRole}</strong> at <strong>{targetCompany}</strong>
            </p>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem' }}>
                AI-generated guidance to help you ace the interview.
            </p>

            <div style={{
                backgroundColor: '#FFF4E6',
                borderRadius: '1rem',
                padding: '1.25rem',
                marginBottom: '2rem',
                border: '1px solid #FFE0B2'
            }}>
                <strong style={{ color: '#E65100' }}>Agent-Generated Guidance</strong>
                <p style={{ marginTop: '0.5rem', lineHeight: '1.6', color: '#E65100', fontSize: '0.95rem' }}>
                    The interview questions, tips, and answering strategies are generated by an agent. They are intended as a guide and may not reflect the actual questions you will be asked.
                </p>
            </div>

            {loading ? (
                <div style={{ textAlign: 'center', padding: '4rem 0' }}>
                    <Loader2 size={40} style={{ margin: '0 auto 1rem', animation: 'spin 1s linear infinite', color: 'var(--primary-color)' }} />
                    <p style={{ color: 'var(--text-secondary)' }}>Generating personalized interview questions...</p>
                </div>
            ) : (
                <div>
                    <h2 style={{ fontSize: '1.3rem', fontWeight: '600', marginBottom: '1rem' }}>Common Interview Questions</h2>
                    <div style={{ display: 'grid', gap: '0.75rem' }}>
                        {interviewQuestions.map((item, idx) => (
                            <div key={idx} style={{
                                backgroundColor: 'var(--surface)',
                                border: '1px solid var(--border-color)',
                                borderRadius: '0.75rem',
                                overflow: 'hidden',
                                boxShadow: '0 1px 3px rgba(0,0,0,0.05)'
                            }}>
                                <button
                                    onClick={() => toggleAccordion(idx)}
                                    style={{
                                        width: '100%',
                                        padding: '1.25rem',
                                        display: 'flex',
                                        justifyContent: 'space-between',
                                        alignItems: 'center',
                                        backgroundColor: openIndex === idx ? 'var(--background)' : 'white',
                                        border: 'none',
                                        cursor: 'pointer',
                                        textAlign: 'left',
                                        transition: 'background-color 0.15s'
                                    }}
                                >
                                    <span style={{ fontWeight: '500', fontSize: '1rem', paddingRight: '1rem' }}>{item.question}</span>
                                    {openIndex === idx ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
                                </button>
                                {openIndex === idx && (
                                    <div className="fade-in" style={{
                                        padding: '1.25rem',
                                        borderTop: '1px solid var(--border-color)',
                                        backgroundColor: 'var(--background)'
                                    }}>
                                        <div style={{
                                            backgroundColor: '#E3F2FD',
                                            padding: '1rem',
                                            borderRadius: '0.5rem',
                                            borderLeft: '4px solid var(--primary-color)'
                                        }}>
                                            <strong style={{ color: 'var(--primary-color)', fontSize: '0.9rem' }}>Answering Strategy:</strong>
                                            <p style={{
                                                color: '#1565C0',
                                                marginTop: '0.5rem',
                                                lineHeight: '1.7',
                                                fontSize: '0.95rem'
                                            }}>
                                                {item.strategy}
                                            </p>
                                        </div>
                                    </div>
                                )}
                            </div>
                        ))}
                    </div>

                    <div style={{
                        marginTop: '2rem',
                        padding: '1.5rem',
                        backgroundColor: 'var(--surface)',
                        borderRadius: '1rem',
                        border: '1px solid var(--border-color)',
                        textAlign: 'center'
                    }}>
                        <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>
                            Want questions for a different role or company?
                        </p>
                        <button
                            onClick={() => window.location.href = '/dashboard'}
                            className="btn btn-primary"
                        >
                            Update Your Target
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}
